tcomproapp/api/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from tastypie.api import Api
from api.resources import ListaResource, ProductoResource, TiendaResource

v1_api = Api(api_name='v1')
v1_api.register(ListaResource())
v1_api.register(ProductoResource())
v1_api.register(TiendaResource())

app_name = 'api'

urlpatterns = [
    url(r'^', include(v1_api.urls)),
]

tcomproapp/apps/cuentas/urls.py
from django.conf.urls import url
from django.urls import path
from . import views
from django.contrib.auth.views import (
    PasswordResetView,
    PasswordResetConfirmView,
    PasswordResetDoneView,
    PasswordResetCompleteView,
)

app_name = 'cuentas'

urlpatterns = [
    url(r'^login/$', views.login_account, name="login_account"),
    url(r'^register/$', views.register, name='register'),
    url(r'^register_thanks/$', views.register_thanks, name='register_thanks'),
    url(r'^logout/$', views.logout_account, name='logout_account'),
    url(r'^recover_password/$', views.recover_password, name='recover_password'),
    url(r'^password_reset', PasswordResetView.as_view(), {
        'template_name':'password_reset_form.html', 
        'email_template_name':'password_reset_email.html'}, name="password_reset"),
    url(r'^reset/password_reset_done', PasswordResetDoneView.as_view(), {'template_name':'registration/password_reset_done.html'}, name="password_reset_done"),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', PasswordResetConfirmView.as_view(),  {'template_name':'cuentas/password_reset_confirm.html'}, name="password_reset_confirm"),
    url(r'^reset/done', PasswordResetCompleteView.as_view(), {'template_name':'registration/password_reset_complete.html'}, name="password_reset_complete"),
]

tcomproapp/tcomproapp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path(r'api/', include('api.urls')),
    path(r'cuenta/', include('apps.cuentas.urls')),
    path(r'producto/', include('apps.productos.urls')),
    path(r'lista/', include('apps.listas.urls')),
    path(r'tienda/', include('apps.tiendas.urls')),
    path(r'', include('apps.web.urls')),
]

tcomproapp/apps/cuentas/models.py
from django.db import models

# Create your models here.

tcomproapp/apps/cuentas/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class SignUpForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, required=True, help_text='Requerido')
    last_name = forms.CharField(max_length=30, required=False, help_text='Opcional.')
    email = forms.EmailField(max_length=254, help_text='Requerido')

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2', )
    
    def __init__(self, *args, **kwargs):
        super(SignUpForm, self).__init__(*args, **kwargs)
        self.fields['first_name'].label = "Nombres"
        self.fields['last_name'].label = "Apellidos"

tcomproapp/apps/cuentas/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout, authenticate
from .forms import SignUpForm

# Create your views here.

def register(request):
    if request.method == 'POST': #validamos que se haya submiteado algo
        form = SignUpForm(request.POST) # Se crea instancia del formulario con la informacion de POST
        if form.is_valid(): # validamos formulario
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('cuentas:register_thanks')
    else:
        form = SignUpForm() # Se crea instancia vacia del formulario
    return render(request, 'cuentas/register.html', {'form':form})

def login_account(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            # Se inicia sesion
            user = form.get_user()
            login(request, user)
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            else:
                return redirect('web:dashboard')
    else:
        form = AuthenticationForm()
    return render(request, 'cuentas/login.html', {'form':form})

def logout_account(request):
    if request.method == 'POST':
        logout(request)
        return redirect('web:home')

def recover_password(request):
    return render(request, 'cuentas/recuperar_pass.html')

def register_thanks(request):
    return render(request, 'cuentas/register_thanks.html')

tcomproapp/templates/cuentas/login.html
{% extends 'base/base.html' %}
{% load static %}

{% block content %}
<!-- INICIAR SESION -->
<div class="content login">
    <!-- Slider
        ================================================== -->
    <section class="page-title bg-theme">
        <div class="container">
            <div class="row">
                <div class="col-12 text-center text-white">
                    <h2>Iniciar Sesión</h2>
                </div>
            </div>
        </div>
    </section>
</div>
<section class="container">
    <div class="row">
        <div class="col-12 col-sm-6 m-auto">
            <form action="{% url 'cuentas:login_account' %}" method="POST" class="bg-light card form-accounts p-4 m-4">
                {% csrf_token %}
                {{ form }}
                {% if request.GET.next %}
                <input type="hidden" name="next" value="{{ request.GET.next }}">
                {% endif %}
                <button class="btn btn-primary btn-block mt-3" type="submit">Iniciar Sesión <i class="fa fa-chevron-right"></i></button>
                <a href="{% url 'cuentas:password_reset' %}" class="mt-3">Recuperar contraseña</a>
            </form>
        </div>
    </div>

</section>

{% endblock %}

tcomproapp/templates/cuentas/recover_password.html
{% extends 'base/base.html' %}
{% load static %}

{% block content %}
<!-- INICIAR SESION -->
<div class="content login">
    <!-- Slider
        ================================================== -->
    <section class="page-title bg-theme">
        <div class="container">
            <div class="row">
                <div class="col-12 text-center text-white">
                    <h2>Recuperar Contraseña</h2>
                </div>
            </div>
        </div>
    </section>
</div>
<section class="container">
    <div class="row">
        <div class="col-12 col-sm-6 m-auto">
            <form action="{% url 'cuentas:recover' %}" method="POST" class="bg-light card form-accounts p-4 m-4">
                {% csrf_token %}
                {{ form }}
                {% if request.GET.next %}
                <input type="hidden" name="next" value="{{ request.GET.next }}">
                {% endif %}
                <button class="btn btn-primary btn-block mt-3" type="submit">Recuperar contraseña <i class="fa fa-chevron-right"></i></button>
            </form>
        </div>
    </div>

</section>

{% endblock %}

tcomproapp/templates/cuentas/register.html
{% extends 'base/base.html' %}
{% load static %}

{% block content %}
<!-- INICIAR SESION -->
<div class="content login">
    <!-- Slider
        ================================================== -->
    <section class="page-title bg-theme">
        <div class="container">
            <div class="row">
                <div class="col-12 text-center text-white">
                    <h2>Registrarme</h2>
                </div>
            </div>
        </div>
    </section>
</div>
<section class="container">
    <div class="row">
        <div class="col-12 col-sm-6 m-auto">
            <form action="{% url 'cuentas:register' %}" method="POST" class="bg-light card form-accounts p-4 m-4">
                {% csrf_token %}
                {{ form }}
                {% if request.GET.next %}
                <input type="hidden" name="next" value="{{ request.GET.next }}">
                {% endif %}
                <button class="btn btn-primary btn-block mt-3" type="submit">Registrarme <i class="fa fa-chevron-right"></i></button>
                <a href="{% url 'cuentas:login_account' %}" class="mt-3">¿Ya tienes una cuenta? Inicia sesión</a>
            </form>
        </div>
    </div>

</section>

{% endblock %}

tcomproapp/templates/cuentas/register_thanks.html
{% extends 'base/base.html' %}
{% load static %}

{% block content %}
<!-- INICIAR SESION -->
<div class="content login">
    <!-- Slider
        ================================================== -->
    <section class="page-title bg-theme">
        <div class="container">
            <div class="row">
                <div class="col-12 text-center text-white">
                    <h2>Registro exitoso</h2>
                </div>
            </div>
        </div>
    </section>
</div>
<section class="container">
    <div class="row">
        <div class="col-12 m-4">
            <div class="jumbotron">
                <h1 class="display-4">¡Bienvenido, {{user.username}}!</h1>
                <p class="lead">Tu registro ha sido exitoso, desde ahora podrás iniciar sesión.</p>
                <hr class="my-4">
                <a class="btn btn-primary btn-lg" href="/" role="button">Ir a Inicio</a>
            </div>
        </div>
    </div>

</section>

{% endblock %}