tcomproapp/api/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from tastypie.api import Api
from api.resources import ListaResource, ProductoResource, TiendaResource

v1_api = Api(api_name='v1')
v1_api.register(ListaResource())
v1_api.register(ProductoResource())
v1_api.register(TiendaResource())

app_name = 'api'

urlpatterns = [
    url(r'^', include(v1_api.urls)),
]

tcomproapp/apps/tiendas/urls.py
from django.conf.urls import include, url
from apps.tiendas import views

app_name = 'tiendas'

urlpatterns = [
    url(r'^$', views.listado, name='listado'),
    url(r'^nuevo$', views.crear, name='crear'),
    url(r'^editar/(?P<id>\d+)/$', views.editar, name='editar'),
    url(r'^eliminar/(?P<id>\d+)/$', views.eliminar, name='eliminar'),
]

tcomproapp/tcomproapp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path(r'api/', include('api.urls')),
    path(r'cuenta/', include('apps.cuentas.urls')),
    path(r'producto/', include('apps.productos.urls')),
    path(r'lista/', include('apps.listas.urls')),
    path(r'tienda/', include('apps.tiendas.urls')),
    path(r'', include('apps.web.urls')),
]

tcomproapp/apps/listas/models.py
from django.db import models

# Create your models here. 

class Lista(models.Model):
    nombre = models.CharField(max_length=50)
    usuario = models.ForeignKey('auth.User', on_delete=models.CASCADE)

    def __str__(self):
        return '{}'.format(self.nombre)

tcomproapp/apps/tiendas/models.py
from django.db import models

# Create your models here.

class Tienda(models.Model):
    tipo_tienda = (
        ('Online', 'Online'),
        ('Fisica', 'Fisica')
    )
    nombre = models.CharField(max_length=50, unique=True)
    sucursal = models.CharField(max_length=50)
    tipo_tienda = models.CharField(max_length=20,choices=tipo_tienda)
    direccion = models.CharField(max_length=50)
    ciudad = models.CharField(max_length=50)
    region = models.CharField(max_length=50)
    foto = models.ImageField(default='default.png', blank=True)
    disponible = models.BooleanField(default=False)

    def __str__(self):
        return '{}'.format(self.nombre)

tcomproapp/apps/tiendas/forms.py
from django import forms

from apps.tiendas.models import Tienda

class RegistroTiendaForm(forms.ModelForm):
    
    class Meta:
        model = Tienda

        fields = [
            'nombre',
            'sucursal',
            'tipo_tienda',
            'direccion',
            'ciudad',
            'region',
            'foto'
        ]
        labels = {
            'nombre' : 'Nombre Tienda',
            'sucursal' : 'Nombre Sucursal',
            'tipo_tienda' : 'Tipo Tienda',
            'direccion' : 'Direccion',
            'ciudad' : 'Ciudad',
            'region' : 'Región',
            'foto' : 'Foto'
        }
        widgets = {
            'nombre' : forms.TextInput(attrs={'class':'form-control'}),
            'sucursal' : forms.TextInput(attrs={'class':'form-control'}),
            'tipo_tienda' : forms.Select(attrs={'class':'form-control'}),
            'direccion' : forms.TextInput(attrs={'class':'form-control'}),
            'ciudad' : forms.TextInput(attrs={'class':'form-control'}),
            'region' : forms.TextInput(attrs={'class':'form-control'}),
        }

class ModificarTienda(forms.ModelForm):
    class Meta:
        model = Tienda
        fields = [
            'nombre',
            'sucursal',
            'tipo_tienda',
            'direccion',
            'ciudad',
            'region',
            'foto'
        ]
        labels = {
            'nombre' : 'Nombre Tienda',
            'sucursal' : 'Nombre Sucursal',
            'tipo_tienda' : 'Tipo Tienda',
            'direccion' : 'Direccion',
            'ciudad' : 'Ciudad',
            'region' : 'Región',
            'foto' : 'Foto'
            
        }
        widgets = {
            'nombre' : forms.TextInput(attrs={'class':'form-control'}),
            'sucursal' : forms.TextInput(attrs={'class':'form-control'}),
            'tipo_tienda' : forms.Select(attrs={'class':'form-control'}),
            'direccion' : forms.TextInput(attrs={'class':'form-control'}),
            'ciudad' : forms.TextInput(attrs={'class':'form-control'}),
            'region' : forms.TextInput(attrs={'class':'form-control'}),
        }

tcomproapp/apps/tiendas/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404

from apps.tiendas.forms import RegistroTiendaForm
from apps.tiendas.forms import ModificarTienda

from apps.tiendas.models import Tienda


# Create your views here.

@login_required()
def listado(request):
    if request.user.is_superuser:
        tienda = Tienda.objects.all() 
    else:
        tienda = Tienda.objects.filter(disponible = 1) 

    contexto = {'tiendas' : tienda}
    return render(request, 'tiendas/listado.html', contexto)


@login_required()
def crear(request):
    if request.method == 'POST':
        form = RegistroTiendaForm(request.POST,request.FILES)
        if form.is_valid():
            form.save()
        return redirect('tiendas:listado')
    else:
        form = RegistroTiendaForm()
    return render(request, 'tiendas/registro.html', {'form':form})

@login_required()
def editar(request, id=None):
    instance = get_object_or_404(Tienda, id=id)
    form = ModificarTienda(request.POST or None, instance=instance)
    if form.is_valid():
        instance = form.save(commit=False)
        instance.save()
        return redirect('tiendas:listado')
    context = {
        "id":instance.id,
        "instance":instance,
        "form":form,
    }
    return render(request, 'tiendas/editar.html', context)

@login_required()
def eliminar(request, id=None):
    instance = get_object_or_404(Tienda, id=id)
    instance.delete()
    return redirect('tiendas:listado')

tcomproapp/templates/tiendas/editar.html
{% extends 'base/base.html' %}

{% block content %}
<div class="content listas editar">
    <section class="container">
        <div class="row">
            <div class="col-12 col-sm-6 m-auto">
                {% if messages %}
                <div class="alert alert-success p-4 m-4" role="alert">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    <h4 class="alert-heading">Tienda editada</h4>
                    <hr>
                    {% for message in messages %}
                    <p>{{ message }}</p>
                    {% endfor %}
                </div>
                {% endif %}
                <form method="POST" enctype="multipart/form-data" class="bg-light card form-accounts p-4 m-4">

                    {% csrf_token %}
                    {{ form.as_p }}
                    <button class="btn btn-primary btn-block mt-3" type="submit">Guardar <i class="fa fa-chevron-right"></i></button>
                    {% if messages %}
                    <ul>
                        {% for message in messages %}
                        <li>{{ message }}</li>
                        {% endfor %}
                    </ul>
                    {% endif %}
                </form>
            </div>
        </div>
    </section>
</div>

{% endblock %}

tcomproapp/templates/tiendas/listado.html
{% extends 'base/base.html' %}

{% block content %}


<div class="content tiendas listado">
    <!-- Page Title
    ================================================== -->
    <section class="page-title bg-theme">
        <div class="container">
            <div class="row">
                <div class="col-12 text-center text-white">
                    <h2>Tiendas</h2>
                </div>
            </div>
        </div>
    </section>

    <div class="container mt-4">
        <div class="row">
            <div class="col-12">
                <a href="{% url 'tiendas:crear' %}" class="btn btn-primary">Agregar Tienda</a>
            </div>
        </div>
        <div class="row mt-4">
            {% for tienda in tiendas %}
            <div class="col-12 col-sm-6 col-lg-4">
                <div class="card mb-4">
                    <img class="card-img-top" src="/media/{{ tienda.foto.url }}" alt="{{ lista.nombre }}">
                    <div class="card-body">
                        <h3 class="card-title">{{ tienda.nombre }}</h3>
                        <h5 class="card-title">Sucursal: {{ tienda.sucursal}}</h5>
                        <h6 class="card-title">Tipo de Tienda: {{ tienda.tipo_tienda}}</h6>
                        <p class="card-text">{{ tienda.direccion }}</p>
                    </div>
                    {% if perms.tienda.change_lista %}
                    <div class="card-footer">
                        {% if tienda.disponible == False %}
                        <button class="btn btn-success js-tienda-aprobar" data-tienda="{{tienda.id}}">Aprobar</button>
                        {%endif%}
                        <a href="{% url 'tiendas:editar' id=tienda.id %}" class="btn btn-primary">Modificar</a>
                        <a href="{% url 'tiendas:eliminar' id=tienda.id %}" class="btn btn-danger">Eliminar</a>
                    </div>
                    {% endif %}
                </div>

            </div>
            {% endfor %}
        </div>
    </div>
</div>

{% endblock %}

tcomproapp/templates/tiendas/registro.html
{% extends 'base/base.html' %}

{% block content %}
<div class="content listas registro">
    <section class="container">
        <div class="row">
            <div class="col-12 col-sm-6 m-auto">
                <div class="alert alert-warning m-4" role="alert">
                    <h4 class="alert-heading">¡Recuerda!</h4>
                    <hr>
                    Luego de agregar una tienda, un administrador deberá aprobar este registro. Esto puede tardar un
                    par de
                    horas.
                </div>
                <form method="POST" enctype="multipart/form-data" class="bg-light card form-accounts p-4 m-4">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button class="btn btn-primary btn-block mt-3" type="submit">Agregar <i class="fa fa-chevron-right"></i></button>
                </form>
            </div>
        </div>
    </section>
</div>

{% endblock %}