tcomproapp/api/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from tastypie.api import Api
from api.resources import ListaResource, ProductoResource, TiendaResource

v1_api = Api(api_name='v1')
v1_api.register(ListaResource())
v1_api.register(ProductoResource())
v1_api.register(TiendaResource())

app_name = 'api'

urlpatterns = [
    url(r'^', include(v1_api.urls)),
]

tcomproapp/apps/cuentas/urls.py
from django.conf.urls import url
from django.urls import path
from . import views
from django.contrib.auth.views import (
    PasswordResetView,
    PasswordResetConfirmView,
    PasswordResetDoneView,
    PasswordResetCompleteView,
)

app_name = 'cuentas'

urlpatterns = [
    url(r'^login/$', views.login_account, name="login_account"),
    url(r'^register/$', views.register, name='register'),
    url(r'^register_thanks/$', views.register_thanks, name='register_thanks'),
    url(r'^logout/$', views.logout_account, name='logout_account'),
    url(r'^recover_password/$', views.recover_password, name='recover_password'),
    url(r'^password_reset', PasswordResetView.as_view(), {
        'template_name':'password_reset_form.html', 
        'email_template_name':'password_reset_email.html'}, name="password_reset"),
    url(r'^reset/password_reset_done', PasswordResetDoneView.as_view(), {'template_name':'registration/password_reset_done.html'}, name="password_reset_done"),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', PasswordResetConfirmView.as_view(),  {'template_name':'cuentas/password_reset_confirm.html'}, name="password_reset_confirm"),
    url(r'^reset/done', PasswordResetCompleteView.as_view(), {'template_name':'registration/password_reset_complete.html'}, name="password_reset_complete"),
]

tcomproapp/apps/listas/urls.py
from django.conf.urls import include, url

from apps.listas import views

app_name = 'listas'

urlpatterns = [
    url(r'^$', views.listado, name='listado'),
    url(r'^nuevo$', views.crear, name='crear'),
    url(r'^(?P<id>\d+)/$', views.lista, name='lista'),
    url(r'^editar/(?P<id>\d+)/$', views.editar, name='editar'),
    url(r'^eliminar/(?P<id>\d+)/$', views.eliminar, name='eliminar'),
]

tcomproapp/apps/tiendas/urls.py
from django.conf.urls import include, url
from apps.tiendas import views

app_name = 'tiendas'

urlpatterns = [
    url(r'^$', views.listado, name='listado'),
    url(r'^nuevo$', views.crear, name='crear'),
    url(r'^editar/(?P<id>\d+)/$', views.editar, name='editar'),
    url(r'^eliminar/(?P<id>\d+)/$', views.eliminar, name='eliminar'),
]

tcomproapp/apps/web/urls.py
from django.urls import path
from django.conf.urls import url
from . import views

app_name = 'web'

urlpatterns = [
    path(r'', views.home, name='home'),
    path(r'dashboard', views.dashboard, name='dashboard'),
]

tcomproapp/tcomproapp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path(r'api/', include('api.urls')),
    path(r'cuenta/', include('apps.cuentas.urls')),
    path(r'producto/', include('apps.productos.urls')),
    path(r'lista/', include('apps.listas.urls')),
    path(r'tienda/', include('apps.tiendas.urls')),
    path(r'', include('apps.web.urls')),
]

tcomproapp/templates/base/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    {% block extrahead %}
    {% endblock %}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/limonte-sweetalert2/7.32.2/sweetalert2.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <link rel="stylesheet" href="{% static 'css/libs/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <title>{% block title %} t-compro app {% endblock %}</title>
</head>

<body>
    {% block header %}
    {% include 'base/header.html' %}
    {% endblock %}
    <main>
        {% block content %}
        <h5>Este es el contenido del archivo base</h5>
        {% endblock %}
    </main>
    {% block footer %}
    {% include 'base/footer.html' %}
    {% endblock %}

    {% block extrajs %}
    {% include 'base/scripts.html' %}
    {% endblock %}
</body>

</html>

tcomproapp/templates/base/footer.html
<!-- Footer
================================================== -->
<footer class="container-fluid py-5 bg-light">
  <div class="container">
    <!-- <div class="row">
      <div class="col-12 col-md">
        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor"
          stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="d-block mb-2">
          <circle cx="12" cy="12" r="10"></circle>
          <line x1="14.31" y1="8" x2="20.05" y2="17.94"></line>
          <line x1="9.69" y1="8" x2="21.17" y2="8"></line>
          <line x1="7.38" y1="12" x2="13.12" y2="2.06"></line>
          <line x1="9.69" y1="16" x2="3.95" y2="6.06"></line>
          <line x1="14.31" y1="16" x2="2.83" y2="16"></line>
          <line x1="16.62" y1="12" x2="10.88" y2="21.94"></line>
        </svg>
      </div>
      <div class="col-6 col-md">
        <h5>Acerca</h5>
        <ul class="list-unstyled text-small">
          <li><a class="text-muted" href="#">Inicio</a></li>
          <li><a class="text-muted" href="#">Nosotros</a></li>
          <li><a class="text-muted" href="#">Contacto</a></li>
          <li><a class="text-muted" href="#">Stuff for developers</a></li>
          <li><a class="text-muted" href="#">Another one</a></li>
          <li><a class="text-muted" href="#">Last time</a></li>
        </ul>
      </div>
      <div class="col-6 col-md">
        <h5>Tiendas</h5>
        <ul class="list-unstyled text-small">
          <li><a class="text-muted" href="#">Resource</a></li>
          <li><a class="text-muted" href="#">Resource name</a></li>
          <li><a class="text-muted" href="#">Another resource</a></li>
          <li><a class="text-muted" href="#">Final resource</a></li>
        </ul>
      </div>
      <div class="col-6 col-md">
        <h5>Resources</h5>
        <ul class="list-unstyled text-small">
          <li><a class="text-muted" href="#">Business</a></li>
          <li><a class="text-muted" href="#">Education</a></li>
          <li><a class="text-muted" href="#">Government</a></li>
          <li><a class="text-muted" href="#">Gaming</a></li>
        </ul>
      </div>
      <div class="col-6 col-md">
        <h5>About</h5>
        <ul class="list-unstyled text-small">
          <li><a class="text-muted" href="#">Team</a></li>
          <li><a class="text-muted" href="#">Locations</a></li>
          <li><a class="text-muted" href="#">Privacy</a></li>
          <li><a class="text-muted" href="#">Terms</a></li>
        </ul>
      </div>
    </div> -->
    <div class="row">
      <p class="text-muted pull-right">&copy; <span class="js-year">2018</span> - TCompro App</p>
    </div>
  </div>
</footer>

tcomproapp/templates/base/header.html
<!-- Header
================================================== -->
<header>
  <nav class="top-bar navbar navbar-expand-md navbar-dark fixed-top bg-dark py-0">
    {% if user.is_authenticated %}
    <span class="text-white">Bienvenido, {{user.username}}</span>
    {% endif %}
    <ul class="navbar-nav ml-auto list-inline">
      {% if user.is_authenticated %}
      <li class="nav-item list-inline-item">
        <form class='logout' action="{% url 'cuentas:logout_account' %}" method="POST">
          {% csrf_token %}
          <button type="submit" class="btn btn-link nav-link">Cerrar Sesión</button>
        </form>
      </li>
      {% else %}
      <li class="nav-item list-inline-item"> <a class="nav-link" href="{% url 'cuentas:login_account' %}">Iniciar
          Sesión</a>
      </li>
      <li class="nav-item list-inline-item"> <a class="nav-link" href="{% url 'cuentas:register' %}">Registro</a>
      </li>
      {% endif %}
    </ul>
  </nav>
  {% if user.is_authenticated %}
  <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-primary mt-20 menu">
    <a class="navbar-brand" href="{% url 'web:dashboard' %}">TComproApp</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#menu-mobile" aria-controls="menu-mobile"
      aria-expanded="false" aria-label="Toggle navigation"> <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="menu-mobile">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item {% if request.path == '/' %} active {% endif %}">
          <a class="nav-link" href="{% url 'web:dashboard' %}">Inicio <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item {% if request.path == '/listas/' %} active {% endif %}">
          <a class="nav-link" href="{% url 'listas:listado' %}">Listas</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'tiendas:listado' %}">Tiendas</a>
        </li>
      </ul>
    </div>
  </nav>
  {% else %}
  <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-primary mt-20 menu">
    <a class="navbar-brand" href="{% url 'web:home' %}">TComproApp</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#menu-mobile" aria-controls="menu-mobile"
      aria-expanded="false" aria-label="Toggle navigation"> <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="menu-mobile">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item {% if request.path == '/' %} active {% endif %}">
          <a class="nav-link" href="{% url 'web:home' %}">Inicio</a>
        </li>
      </ul>
    </div>
  </nav>
  {% endif %}

</header>

tcomproapp/templates/base/scripts.html
{% load staticfiles %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.js" integrity="sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60="
    crossorigin="anonymous"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/limonte-sweetalert2/7.32.2/sweetalert2.all.min.js"></script>

<script src="{% static 'js/libs/bootstrap.min.js' %}"></script>
<script src="{% static 'js/main.js' %}"></script>