tcomproapp/api/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from tastypie.api import Api
from api.resources import ListaResource, ProductoResource, TiendaResource

v1_api = Api(api_name='v1')
v1_api.register(ListaResource())
v1_api.register(ProductoResource())
v1_api.register(TiendaResource())

app_name = 'api'

urlpatterns = [
    url(r'^', include(v1_api.urls)),
]

tcomproapp/apps/listas/urls.py
from django.conf.urls import include, url

from apps.listas import views

app_name = 'listas'

urlpatterns = [
    url(r'^$', views.listado, name='listado'),
    url(r'^nuevo$', views.crear, name='crear'),
    url(r'^(?P<id>\d+)/$', views.lista, name='lista'),
    url(r'^editar/(?P<id>\d+)/$', views.editar, name='editar'),
    url(r'^eliminar/(?P<id>\d+)/$', views.eliminar, name='eliminar'),
]

tcomproapp/tcomproapp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path(r'api/', include('api.urls')),
    path(r'cuenta/', include('apps.cuentas.urls')),
    path(r'producto/', include('apps.productos.urls')),
    path(r'lista/', include('apps.listas.urls')),
    path(r'tienda/', include('apps.tiendas.urls')),
    path(r'', include('apps.web.urls')),
]

tcomproapp/apps/listas/models.py
from django.db import models

# Create your models here. 

class Lista(models.Model):
    nombre = models.CharField(max_length=50)
    usuario = models.ForeignKey('auth.User', on_delete=models.CASCADE)

    def __str__(self):
        return '{}'.format(self.nombre)

tcomproapp/apps/listas/forms.py
from django import forms

from apps.listas.models import Lista

class RegistroListaForm(forms.ModelForm):
    class Meta:
        model = Lista

        fields = [
            'nombre',
        ]
        labels = {
            'nombre' : 'Nombre de la Lista',
        }
        widgets = {
            'nombre' : forms.TextInput(attrs={'class':'form-control'}),
        }

class ModificarLista(forms.ModelForm):
    class Meta:
        model = Lista
        fields = [
            'nombre',
        ]
        labels = {
            'nombre' : 'Nombre Lista',            
        }
        widgets = {
            'nombre' : forms.TextInput(attrs={'class':'form-control'}),
        }

tcomproapp/apps/listas/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404

from . import forms

from apps.listas.models import Lista

# Create your views here.

@login_required()
def crear(request):
    if request.method == 'POST':
        form = forms.RegistroListaForm(request.POST,request.FILES)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.usuario_id = request.user.id
            form.save()
            messages.success(request, 'Se ha registrado lista exitosamente')
        return redirect('listas:listado')
    else:
        form = forms.RegistroListaForm()
    return render(request, 'listas/registro.html', {'form':form})

@login_required()
def listado(request):
    lista = Lista.objects.filter(usuario=request.user.id)
    contexto = {'listas' : lista}
    return render(request, 'listas/listado.html', contexto)

@login_required()
def editar(request, id=None):
    instance = get_object_or_404(Lista, id=id)
    form = forms.ModificarLista(request.POST or None, instance=instance)
    if form.is_valid():
        instance = form.save(commit=False)
        instance.save()
        return redirect('listas:listado')
    context = {
        "id":instance.id,
        "instance":instance,
        "form":form,
    }
    return render(request, 'listas/editar.html', context)

@login_required()
def eliminar(request, id=None):
    instance = get_object_or_404(Lista, id=id)
    instance.delete()
    return redirect('listas:listado')

@login_required()
def lista(request, id=None):
    instance = get_object_or_404(Lista, id=id)
    contexto = {'lista' : instance}
    return render(request, 'listas/lista.html', contexto)

tcomproapp/templates/listas/editar.html
{% extends 'base/base.html' %}

{% block content %}
<div class="content listas editar">
    <section class="container">
        <div class="row">
            <div class="col-12 col-sm-6 m-auto">
                {% if messages %}
                <div class="alert alert-success p-4 m-4" role="alert">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    <h4 class="alert-heading">Tienda editada</h4>
                    <hr>
                    {% for message in messages %}
                    <p>{{ message }}</p>
                    {% endfor %}
                </div>
                {% endif %}
                <form method="POST" enctype="multipart/form-data" class="bg-light card form-accounts p-4 m-4">

                    {% csrf_token %}
                    {{ form.as_p }}
                    <button class="btn btn-primary btn-block mt-3" type="submit">Guardar <i class="fa fa-chevron-right"></i></button>
                    {% if messages %}
                    <ul>
                        {% for message in messages %}
                        <li>{{ message }}</li>
                        {% endfor %}
                    </ul>
                    {% endif %}
                </form>
            </div>
        </div>
    </section>
</div>

{% endblock %}

tcomproapp/templates/listas/lista.html
{% extends 'base/base.html' %}

{% block content %}
{% csrf_token %}
<div class="d-none js-id-lista">{{lista.id}}</div>
<div class="content listas lista-interna">
    <!-- Page Title
    ================================================== -->
    <section class="page-title bg-theme">
        <div class="container">
            <div class="row">
                <div class="col-12 text-center text-white">
                    <h2>Lista {{lista.nombre}}</h2>
                </div>
            </div>
        </div>
    </section>

    <div class="container mt-4 pb-5 border-bottom">
        <div class="row">
            <div class="col-xl-3 col-sm-6 py-2">
                <div class="card bg-success text-white h-100">
                    <div class="card-body bg-success">
                        <div class="rotate">
                            <i class="fa fa-user fa-4x"></i>
                        </div>
                        <h6 class="text-uppercase">Productos</h6>
                        <h1 class="display-4"><span class="js-cant-productos">----</span></h1>
                    </div>
                </div>
            </div>
            <div class="col-xl-3 col-sm-6 py-2">
                <div class="card text-white bg-info h-100">
                    <div class="card-body bg-info">
                        <div class="rotate">
                            <i class="fa fa-list fa-4x"></i>
                        </div>
                        <h6 class="text-uppercase">Productos comprados</h6>
                        <h1 class="display-4"><span class="js-cant-productos-comprados">----</span></h1>
                    </div>
                </div>
            </div>
            <div class="col-xl-3 col-sm-6 py-2">
                <div class="card text-white bg-danger h-100">
                    <div class="card-body bg-danger">
                        <div class="rotate">
                            <i class="fa fa-twitter fa-4x"></i>
                        </div>
                        <h6 class="text-uppercase">Costo presupuestado</h6>
                        <h1 class="display-4">$<span class="js-total-presupuestado">----</span></h1>
                    </div>
                </div>
            </div>
            <div class="col-xl-3 col-sm-6 py-2">
                <div class="card text-white bg-warning h-100">
                    <div class="card-body">
                        <div class="rotate">
                            <i class="fa fa-share fa-4x"></i>
                        </div>
                        <h6 class="text-uppercase">Costo real</h6>
                        <h1 class="display-4">$ <span class="js-total-real"></span></h1>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="row my-4">
            <div class="col-12">
                <h2 class="d-1">Listado de productos</h2>
            </div>
            <div class="col-12 my-3">
                <button class="btn btn-sm btn-success js-reload-productos" data-toggle="modal" data-target="#agregarProductoModal">
                    <i class="fa fa-refresh mr-2"></i>Agregar producto</button>
                <button class="btn btn-sm btn-primary js-reload-productos">
                    <i class="fa fa-refresh mr-2"></i>Refrescar tabla</button>
            </div>

            <div class="col-12">
                <table class="mt-2 table productos">
                    <thead class="thead-dark">
                        <tr>
                            <th scope="col">Nombre</th>
                            <th scope="col">Tienda</th>
                            <th scope="col">Notas</th>
                            <th scope="col">Comprado</th>
                            <th scope="col">Acciones</th>
                        </tr>
                    </thead>
                    <tbody>

                    </tbody>
                </table>
            </div>


        </div>
    </div>
</div>
</div>

<!-- Modal Agregar Producto-->
<div class="modal fade" id="agregarProductoModal" tabindex="-1" role="dialog" aria-labelledby="agregarProductoModalLabel"
    aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="agregarProductoModalLabel">Agregar Producto</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form>
                    <div class="form-group">
                        <label for="recipient-name" class="col-form-label">Nombre:</label>
                        <input type="text" class="form-control js-add-producto-nombre" id="nombre" required>
                    </div>
                    <div class="form-group">
                        <label for="recipient-name" class="col-form-label">Costo Presupuestado:</label>
                        <input type="number" class="form-control js-add-producto-costo-presupuestado" id="costo_presupuestado"
                            required>
                    </div>
                    <div class="form-group">
                        <label for="recipient-name" class="col-form-label">Costo Real:</label>
                        <input type="number" class="form-control js-add-producto-costo-real" id="costo">
                    </div>
                    <div class="form-group">
                        <label for="recipient-name" class="col-form-label">Tienda:</label>
                        <select class="form-control js-tiendas-select" required>
                            <option selected disabled>Selecciona una tienda</option>
                        </select>
                    </div>
                    <div class="form-group">
                        <label for="message-text" class="col-form-label">Notas Adicionales:</label>
                        <textarea class="form-control js-add-producto-notas" required></textarea>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                <button type="button" type="submit" class="btn btn-success js-add-producto">Agregar</button>
            </div>
        </div>
    </div>
</div>
{% endblock %}

tcomproapp/templates/listas/listado.html
{% extends 'base/base.html' %}

{% block content %}


<div class="content listas listado">
    <!-- Page Title
    ================================================== -->
    <section class="page-title bg-theme">
        <div class="container">
            <div class="row">
                <div class="col-12 text-center text-white">
                    <h2>Mis Listas</h2>
                </div>
            </div>
        </div>
    </section>

    <div class="container mt-4">
        <div class="row">
            <div class="col-12">
                <a class="btn btn-primary" href="{% url 'listas:crear' %}">Agregar lista</a>
            </div>
        </div>

        <div class="row mt-4">
            {% for lista in listas %}
            <div class="col-12 col-sm-6 col-lg-4">
                <div class="card mb-4">
                    <img class="card-img-top" src="#" alt="{{ lista.nombre_lista }}">
                    <div class="card-body">
                        <h3 class="card-title">{{ lista.nombre }}</h3>
                        <h6 class="">Creado por {{ lista.usuario }}</h6>
                    </div>
                    <div class="card-footer">
                        <a href="{% url 'listas:lista' id=lista.id %}" class="btn btn-primary">Ver</a>
                        <a href="{% url 'listas:editar' id=lista.id %}" class="btn btn-primary">Modificar</a>
                        <a href="{% url 'listas:eliminar' id=lista.id %}" class="btn btn-danger">Eliminar</a>
                    </div>
                </div>

            </div>
            {% endfor %}

        </div>
    </div>
</div>

{% endblock %}

tcomproapp/templates/listas/registro.html
{% extends 'base/base.html' %}

{% block content %}
<div class="content listas registro">
    <section class="container">
        <div class="row">
            <div class="col-12 col-sm-6 m-auto">
                <form method="POST" enctype="multipart/form-data" class="bg-light card form-accounts p-4 m-4">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button class="btn btn-primary btn-block mt-3" type="submit">Agregar <i class="fa fa-chevron-right"></i></button>
                    {% if messages %}
                    <ul class="messages">
                        {% for message in messages %}
                        <li {% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
                        {% endfor %}
                    </ul>
                    {% endif %}
                </form>
            </div>
        </div>
    </section>
</div>

{% endblock %}